# Data Import and Clean up
    # Data Import and Clean Up covered in this Notebook - API DATA Calls.ipynb
    # SMAs Continued in the SMAs.ipnb notebook to modularize the code

In [ ]:
def data_import_cleanup_function()
    #Bitcoin historical daily prices USD
    #Source: https://data.nasdaq.com/data/BCHAIN/MKPRU-bitcoin-market-price-usd
    #btc_price = quandl.get('BCHAIN/MKPRU')
    #btc_price.rename(columns={"Value":"BTC Price"}, inplace=True)
    #btc_price.head()

    #Yfinance to replace Quandl
    btc = yf.Ticker("BTC-USD")
    btc_data = btc.history(period="max")
    #btc_data = btc_data.drop
    #btc_data.head()
    
    #Etherium historical daily prices USD
    eth = yf.Ticker("ETH-USD")
    eth_data = eth.history(period="max")
    #eth_data.head()
    
    #Consumer Sentiment Data
    #Source: https://data.nasdaq.com/data/UMICH/SOC35-university-of-michigan-consumer-surveybuying-conditions-for-large-household-goods
    #consumer_sentiment = quandl.get("UMICH/SOC35")
    #consumer_sentiment.head()

In [5]:
    #Fear and Greed Index API call
    #source:https://alternative.me/crypto/fear-and-greed-index/
    response = urlopen("https://api.alternative.me/fng/?limit=0&date_format=us")
    json_data = response.read().decode('utf-8', 'replace')
    raw_fear_greed = json.loads(json_data)

    #Flatten json data
    fear_greed = pd.json_normalize(raw_fear_greed['data'])
    fear_greed = fear_greed.set_index("timestamp")
    fear_greed.index.names = ["Date"]
    fear_greed.index = pd.to_datetime(fear_greed.index)
    fear_greed = fear_greed.drop(columns="time_until_update")
    fear_greed.tail()
    #fear_greed.head()

           value value_classification
Date
2018-02-05    11         Extreme Fear
2018-02-04    24         Extreme Fear
2018-02-03    40                 Fear
2018-02-02    15         Extreme Fear
2018-02-01    30                 Fear

In [6]:
    #Combined dataframes
    combined_values = pd.concat([eth_data, fear_greed], join="inner", axis=1)

    combined_values.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,value,value_classification
Date,,,,,,,,,
2018-02-01,1119.369995,1161.349976,984.818970,1036.790039,5261680128,0,0,30,Fear
2018-02-02,1035.770020,1035.770020,757.979980,915.784973,6713290240,0,0,15,Extreme Fear
2018-02-03,919.210999,991.942993,847.690002,964.018982,3243480064,0,0,40,Fear
2018-02-04,964.666992,969.031982,805.064026,834.682007,2997090048,0,0,24,Extreme Fear
2018-02-05,834.958008,856.645996,644.598999,697.950989,4269530112,0,0,11,Extreme Fear

In [7]:
    #Testing option for merged call to streamline API calls from quandl

    #API call for merged dataset with BTC, ETH and Fear/Greed
    #merged_dataset = quandl.MergedDataset([('WIKI/AAPL', {'column_index': [11]}), ('WIKI/MSFT', {'column_index': [9,11]}), 'WIKI/TWTR'])

    #Get data for merged data set
    #data = merged_dataset.data()

    #Review data set
    #display(data)

In [8]:
    # Store Datafrome in memory
    return %store combined_values

Stored 'combined_values' (DataFrame)